name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: actions
    env:
      FONT_AWESOME_TOKEN: ${{ secrets.FONT_AWESOME_TOKEN }}
    defaults:
      run:
        working-directory: rent-history
    steps:
      - name: Checkout rent-history
        uses: actions/checkout@v4
        with:
          path: rent-history

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: rent-history/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check formatting
        run: yarn format:check

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
